apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-service" .Chart.Name | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: {{ .Values.containerPort }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
  selector:
    app: {{ .Chart.Name }}
